apiVersion: v1
kind: Secret
metadata:
  name: lambda-mcp-aws-credentials
  namespace: lambda-mcp
  labels:
    app: lambda-performance-mcp
type: Opaque
data:
  # Base64 encoded AWS credentials
  # Replace these with your actual base64-encoded credentials
  # echo -n "your-access-key" | base64
  # echo -n "your-secret-key" | base64
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
---
# Example of using AWS IAM Service Account (recommended for EKS)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lambda-mcp-service-account
  namespace: lambda-mcp
  labels:
    app: lambda-performance-mcp
  annotations:
    # Replace with your actual IAM role ARN
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT-ID:role/lambda-mcp-role
automountServiceAccountToken: true